package hjsc_project;

import java.util.List;


public class ProfileGUI extends javax.swing.JFrame {
    private SwimmingSchool swimmingSchool;
    private String user_name;
    
    /**
     * Creates new form ProfileGUI
     */
    public ProfileGUI(SwimmingSchool swimmingSchool) {
        this.swimmingSchool = swimmingSchool;
        this.user_name = swimmingSchool.getUser_name();
        initComponents();
        learnerProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        f_nameField = new javax.swing.JTextField();
        nameLabel1 = new javax.swing.JLabel();
        u_nameField = new javax.swing.JTextField();
        nameLabel2 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        nameLabel3 = new javax.swing.JLabel();
        contactField = new javax.swing.JTextField();
        nameLabel4 = new javax.swing.JLabel();
        gradeField = new javax.swing.JTextField();
        nameLabel5 = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        nameLabel6 = new javax.swing.JLabel();
        genderField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1530, 830));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1530, 830));

        profilePanel.setBackground(new java.awt.Color(255, 255, 255));
        profilePanel.setLayout(null);

        nameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLabel.setText("Full Name   :");
        profilePanel.add(nameLabel);
        nameLabel.setBounds(60, 90, 90, 17);

        f_nameField.setEditable(false);
        f_nameField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        profilePanel.add(f_nameField);
        f_nameField.setBounds(160, 80, 270, 40);

        nameLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLabel1.setText("User Name :");
        profilePanel.add(nameLabel1);
        nameLabel1.setBounds(60, 210, 90, 17);

        u_nameField.setEditable(false);
        u_nameField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        profilePanel.add(u_nameField);
        u_nameField.setBounds(160, 200, 270, 40);

        nameLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLabel2.setText("Email           :");
        profilePanel.add(nameLabel2);
        nameLabel2.setBounds(60, 330, 90, 17);

        emailField.setEditable(false);
        emailField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        profilePanel.add(emailField);
        emailField.setBounds(160, 320, 270, 40);

        nameLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLabel3.setText("Contactt      :");
        profilePanel.add(nameLabel3);
        nameLabel3.setBounds(60, 450, 90, 17);

        contactField.setEditable(false);
        contactField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        profilePanel.add(contactField);
        contactField.setBounds(160, 440, 270, 40);

        nameLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLabel4.setText("Grade         :");
        profilePanel.add(nameLabel4);
        nameLabel4.setBounds(60, 150, 90, 17);

        gradeField.setEditable(false);
        gradeField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        profilePanel.add(gradeField);
        gradeField.setBounds(160, 140, 270, 40);

        nameLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLabel5.setText("Age             :");
        profilePanel.add(nameLabel5);
        nameLabel5.setBounds(60, 270, 90, 17);

        ageField.setEditable(false);
        ageField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        profilePanel.add(ageField);
        ageField.setBounds(160, 260, 270, 40);

        nameLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLabel6.setText("Gender       :");
        profilePanel.add(nameLabel6);
        nameLabel6.setBounds(60, 390, 90, 17);

        genderField.setEditable(false);
        genderField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        profilePanel.add(genderField);
        genderField.setBounds(160, 380, 270, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Learner Profile");
        profilePanel.add(jLabel2);
        jLabel2.setBounds(180, 30, 210, 22);

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        profilePanel.add(backButton);
        backButton.setBounds(140, 510, 216, 40);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hjsc_project/image/hjsc2.jpg"))); // NOI18N
        jLabel5.setToolTipText("");
        jLabel5.setAlignmentX(0.5F);
        jLabel5.setPreferredSize(new java.awt.Dimension(700, 500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1530, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        new DashboardGUI(swimmingSchool).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    //show learner profile
    public void learnerProfile() {
        //get learners details by for loop
        List<User> users = swimmingSchool.getLearners();
        for (User user : users) {
            if (user.getUser_name().equalsIgnoreCase(user_name)) {
                String full_name = user.getFull_name();
                String u_name = user.getUser_name();
                String email = user.getUser_email();
                String age=user.getUser_age();
                String contact = user.getUser_contact();
                String grade = user.getUser_grade();
                String gender = user.getUser_gender();
                //print learner details
                f_nameField.setText(full_name);
                u_nameField.setText(u_name);
                emailField.setText(email);
                ageField.setText(age);
                contactField.setText(contact);
                gradeField.setText(grade);
                genderField.setText(gender);
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField contactField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField f_nameField;
    private javax.swing.JTextField genderField;
    private javax.swing.JTextField gradeField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JLabel nameLabel4;
    private javax.swing.JLabel nameLabel5;
    private javax.swing.JLabel nameLabel6;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JTextField u_nameField;
    // End of variables declaration//GEN-END:variables
}
